"""
Django settings for Smart_Office project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
# Your buddy Jacob was here
import os
import socket
from ntpath import normpath, join

# SECURITY WARNING: keep the secret key used in production secret!
ENCRYPT_KEY = "CHq90ub8fNSmxAMN7A4G_Qrl5GK6HfML-b7YKh3Qn1o="
SECRET_KEY = '0927tcy^(3kq^#eu!+w4(dd)77(c-w3i8yyr$kj%chpu-8k&2m'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# # Allow CORS Access (ALL)
# CORS_ORIGIN_ALLOW_ALL = False
PROD_SERVER_LIST = ['office.fii-corp.com', '10.18.128.98', '63.96.45.210', 'http://63.96.45.210/']
TEST_SERVER_LIST = ['127.0.0.1', '10.20.193.67']
ALLOWED_HOSTS = TEST_SERVER_LIST + PROD_SERVER_LIST
SERVER_NAME = socket.gethostbyname(socket.gethostname())
SERVER_LIST = ['10.20.193.67', '10.18.128.98']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'office_app',
    'smart_hr',
    'travel',
    'it_app',
    'background_scheduler.apps.BackgroundSchedulerConfig',
    'purchase',
    'expense',
    'goods_received',
    'mro_invoice',
    'visitor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Smart_Office.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_base_url.context_processors.base_url',
            ],
        },
    },
]

AUTH_USER_MODEL = 'office_app.Account'

WSGI_APPLICATION = 'Smart_Office.wsgi.application'
#
# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'so_test', #test #smart_office
#         'PASSWORD': 'ssy3.1415926',#password
#         'HOST': 'localhost',  # Test Database => 10.20.193.61  Prod Database => 59
#         'PORT': '5432',
#     },
# }         'USER': 'postgres',
#
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'smart_office', #test #smart_office
        'USER': 'postgres',
        'PASSWORD': 'password',
        'HOST': '10.20.193.61',  #10.20.193.61, # Test Database => 61  Prod Database => 59
        'PORT': '5432',
    },
}
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Chicago'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'admin.smartoffice@fii-corp.com'
# EMAIL_HOST_PASSWORD = 'foxconn1!'

# Login, logout redirects
LOGIN_REDIRECT_URL = 'smart_office_dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Static files (CSS, JavaScript, Images) and Upload settings
# https://docs.djangoproject.com/en/3.0/howto/static-files/
if SERVER_NAME in SERVER_LIST:
    MEDIA_ROOT = '/var/www/html/media/'
    STATIC_ROOT = '/var/www/html/static'
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000000

# Base URL of the site
BASE_URL = 'http://127.0.0.1:8000'

# Site Administration Email Address
SITE_ADMIN_EMAIL = "admin.smartoffice@fii-corp.com"

# Date format from input
DATE_INPUT_FORMATS = ['%m/%d/%Y']
